baseurl = "http://wwww.olivierfredon.com"
title = "Olivier Fredon - Designer et concepteur Web freelance"
languageCode = "fr"
theme = "curiosity"

pluralizeListTitles = false
enableInlineShortcodes = true

[params]
    author = "Olivier Fredon"
    pseudo = "the2ne"
    description = "Olivier Fredon - Designer et concepteur Web freelance: communication, Print, Web & UI Design, intégration, gestion de projet"

[taxonomies]
    category = "categories"
    tag = "tags"

[[menu.main]]
    name = "Blog"
    pre = ""
    url = "/blog/"
    identifier = "blog"
    weight = 1
#[[menu.main]]
#    name = "Portfolio"
#    pre = ""
#    url = "/portfolio/"
#    identifier = "portfolio"
#    weight = 2
#[[menu.main]]
#    name = "A propos"
#    pre = ""
#    url = "/a-propos/"
#    identifier = "apropos"
#    weight = 3
