baseurl = "http://wwww.olivierfredon.com"
title = "Olivier Fredon - Designer et concepteur Web freelance"
languageCode = "fr"
theme = "curiosity"

pluralizeListTitles = false
enableInlineShortcodes = true

[params]
    author = "Olivier Fredon"
    pseudo = "the2ne"
    description = "Olivier Fredon - Designer et concepteur Web freelance: communication, Print, Web & UI Design, intégration, gestion de projet"

[taxonomies]
    category = "categories"
    tag = "tags"

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 1
[[menu.main]]
    name = "Contact"
    url = "mailto:contact@olivier.fredon.com"
    weight = 2
